# Generated by Django 5.2.4 on 2025-08-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='User', max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField()),
                ('report', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
