# Generated by Django 5.2.4 on 2025-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_report',
            field=models.FileField(null=True, upload_to='Files/%y/%m/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m'),
        ),
    ]
