# Generated by Django 5.2.4 on 2025-08-29 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(default='User', max_length=30, validators=[django.core.validators.RegexValidator(message='الاسم الأول يجب أن يبدأ بحرف Capital ويحتوي على أحرف فقط.', regex='^[A-Z][a-zA-Z]*$')]),
        ),
    ]
